# This workflow runs automatically on pushes to master.
# It can also be run manually via workflow_dispatch. It uses check-if-branch-should-deploy
# to prevent cluttering the deployments list with initial release-hotfix- branches.
#
# - Build: Compiles the app and runs tests

name: Post-merge

on:
    push:
        branches:
            - master
            - 'release-hotfix-*'
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    deployments: read
    pull-requests: read

jobs:

    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4.1.7
            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.1
              with:
                  dotnet-version: '9.x'
            - name: Build
              run: dotnet build --no-incremental --configuration Release /p:WarningsAsErrors=true /warnaserror
            - name: Test
              run: dotnet test
