# This workflow runs automatically on pushes to main.
# It can also be run manually via workflow_dispatch. It uses check-if-branch-should-deploy
# to prevent cluttering the deployments list with initial release-hotfix- branches.
#
# - Build: Compiles the app and runs tests

name: Post-merge

on:
    push:
        branches:
            - main
            - 'release-hotfix-*'
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    deployments: read
    pull-requests: read

jobs:

    build_and_test:
        name: Build and test
        runs-on: windows-latest
        steps:

            - name: Checkout source code
              uses: actions/checkout@v4.2.2

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.3.0
              with:
                  global-json-file: "./global.json"
                  cache: true
                  cache-dependency-path: "Directory.Packages.props"

            # Use Release-Optimized configuration for post-merge which performs expensive optimization and trimming operations.
            - name: Build
              run: dotnet build --no-incremental --configuration Release-Optimized /p:WarningsAsErrors=true /warnaserror

            #TODO package

            #TODO deploy
