name: Pre-merge

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '**'

jobs:
    build_and_test:
        if: ${{ !github.event.pull_request.draft }}
        name: Build and test
        runs-on: windows-latest
        environment:
            name: qa-tests
        steps:

            - name: Checkout source code
              uses: actions/checkout@v4.2.2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.3.0
              with:
                  global-json-file: "./global.json"
                  cache: true
                  cache-dependency-path: "Directory.Packages.props"

            # Use Release configuration for pre-merge because it doesn't perform expensive optimizations (compared to Release-Optimized).
            - name: Build
              run: dotnet build --no-incremental --configuration Release /p:WarningsAsErrors=true /warnaserror

            - name: Test
              run: |
                  dotnet test \
                      --configuration Release \
                      --no-build \
                      -e DOTNET_ENVIRONMENT="${{ vars.DOTNET_ENVIRONMENT }}"
