name: Pre-merge

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '**'
permissions:
    contents: read
    actions: read
    checks: write
jobs:
    build_and_test:
        if: ${{ !github.event.pull_request.draft }}
        name: Build and test
        runs-on: windows-latest
        environment:
            name: qa-tests
        steps:

            - name: Checkout source code
              uses: actions/checkout@v4.2.2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.3.0
              with:
                  global-json-file: "./global.json"
                  cache: true
                  cache-dependency-path: "Directory.Packages.props"

            # Use Release configuration for pre-merge because it doesn't perform expensive optimizations (compared to Release-Optimized).
            - name: Build
              run: dotnet build --no-incremental --configuration Release /p:WarningsAsErrors=true /warnaserror

            - name: Test
              run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" -e DOTNET_ENVIRONMENT="${{ vars.DOTNET_ENVIRONMENT }}"

            - name: Test Results
              uses: dorny/test-reporter@v2.0.0
              if: success() || failure()
              with:
                name: Test Results
                path: tests/**/*.trx
                reporter: dotnet-trx

            - name: Upload Test Results Artifacts
              uses: actions/upload-artifact@v4.6.1
              if: success() || failure()
              with:
                  include-hidden-files: true
                  name: test-results-with-screenshots
                  path: tests/**/TestResults/**/*
